### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by Odianosen25** [theolind/pymysensors#176]
Hello @MartinHjelmare,

many thanks for your work

I am working on a project whereby I have an external TCP server I want the mySensor gateway to connect to, but the data from the server is sent to another system for parsing.

This way I need not use the 

```GATEWAY = mysensors.TCPGateway(
  '127.0.0.1', port=5003, timeout=1.0, reconnect_timeout=10.0,
  event_callback=event, persistence=True,
  persistence_file='somefolder/mysensors.pickle', protocol_version='1.4')```

Based on this, what is the best way to use your code, if I skip this part? Will it all work, and can I use use your library to parse what I receive from my TCP server?

Regards

**Comment by MartinHjelmare** [comment]
Hi!

The message handling entrypoint is the `logic` method on the gateway instance. So if you implement your own transport, but want to keep using the message handlers of the library, you need to call `logic` with the message string.

Some messages will not be returned directly by the `logic` method, but saved on `Sensor` specific FIFO queues and state buffers. This happens when a node is smartsleeping. When we receive a wake up message from a node the FIFO queue and state buffer of the node will be emptied and put on the main message queue. To get messages from the main message queue, use the `run_job` method.

Let me know if that helps you or if you have more questions.

**Comment by Odianosen25** [comment]
Hello @MartinHjelmare,

Many thanks for the kind and prompt response. Unfortunately I didn't fully grasp what you were trying to say. I did understand, but I have gone via the gateway files and found no `logic` method; please apologies if I am missing the obvious.

Can you kindly give me an example code based on the following?

- I setup my own transport as you said, then which method do I pass it to
- Things like `persistence` and `persistence_file`, how exactly do I handle it?

Thanks and regards

**Comment by MartinHjelmare** [comment]
The `logic` method is here:
https://github.com/theolind/pymysensors/blob/master/mysensors/__init__.py#L63

I recommend reading the tests for examples on how to use the gateway without a transport. Eg:
https://github.com/theolind/pymysensors/blob/master/tests/test_mysensors.py#L141-L147
https://github.com/theolind/pymysensors/blob/master/tests/test_mysensors.py#L221-L226
https://github.com/theolind/pymysensors/blob/master/tests/test_mysensors.py#L248-L254

You can read about persistence here:
https://github.com/theolind/pymysensors/blob/master/README.md#persistence

To alert the gateway that a new message has come in and need saving, call the `alert` method passing the message instance:
https://github.com/theolind/pymysensors/blob/master/mysensors/__init__.py#L83

**Comment by Odianosen25** [comment]
Many thanks for this good sir, will be closing now.

Kind regards
