### ISSUE TITLE
Questions about running on Raspberry Pi

### ISSUE THREAD

**Issue by flatsiedatsie** [theolind/pymysensors#195]
I am trying to develop an [add-on](https://github.com/mozilla-iot/gateway-addon-python) for the [Mozilla Gateway](https://github.com/mozilla-iot/gateway) that will allow it to connect to MySensors devices.

- On the Raspberry Pi, does the official MySensors software still need to be installed if I want to use this? Or does this project communicate "directly"?
- How would enabling encryption and signing fit in? I suspect the easiest way to have an encrypted network is to connect an Arduino Nano that acts as gateway via the USB (and thus serial) port?
- Could this be used to talk to an NRF24L01 radio that is directly connected to the GPIO pins somehow? And would encryption then still be possible, or would that require extra code to support that?

**Comment by MartinHjelmare** [comment]
Pymysensors just enables a computer to talk to a MySensors gateway via its serial api, over serial connection, mqtt or tcp. Pymysensors doesn't know anything about the radio protocol that MySensors use, since that isn't required to talk to the gateway.

- Yes, since pymysensors only communicates with the gateway.
- Doesn't apply, since those features are part of the radio network.
- No, see above.

**Comment by flatsiedatsie** [comment]
About the first question: if a serial Arduino Nano gateway is used, then it doesn't seem necessary to install the MySensors gateway software onto the Raspberry Pi too.

**Comment by MartinHjelmare** [comment]
That's correct. These questions doesn't have anything to do with pymysensors. It's better to ask about this at mysensors.org.
