### ISSUE TITLE
Protocol version - why version 1.4 by default?

### ISSUE THREAD

**Issue by flatsiedatsie** [theolind/pymysensors#196]
What are the possible options for the protocol version? Is there a reason version 1.4 is used by default, and not the latest supported version? (would that be 2.2?)

**Comment by MartinHjelmare** [comment]
Here are the versions that will give an effect. Specifying a lower version that 1.4 will default to 1.4. Specifying a higher version than 2.2 will default to 2.2.

The default is 1.4 since it has been the default since early days of the library. Changing it would be a breaking change. I have also considered it though. I think it would be better to default to latest supported version, if version is omitted.

On the other hand, we could ask the gateway for the correct version and use that. That would be the best.
