### ISSUE TITLE
Two nodes sharing the same ID

### ISSUE THREAD

**Issue by flatsiedatsie** [theolind/pymysensors#207]
Two of my nodes seem to have gotten the same node ID.

In my system I don't use persistence. Is that what could have caused this?

![mixed-devices](https://user-images.githubusercontent.com/805405/56864883-68d17580-69b7-11e9-9b4c-0da7001b8c1e.png)
_The CO2 sensor value in the top right corner should not be there._

**Comment by MartinHjelmare** [comment]
Are you using static node ids defined in the sketch or requesting node ids from the controller? If a node id has ever been stored in the eeprom the eeprom needs to be cleared to reset the node id and allow auto requesting.

**Comment by flatsiedatsie** [comment]
No, I'm not using static node ID. Perhaps the new device had an old ID. But it's happened twice now. I thought it was perhaps my choice to disable persistence.

**Comment by MartinHjelmare** [comment]
A node will only request a node ID if it hasn't stored one in eeprom. So once the node has received the node ID, it shouldn't request it again even if you restart it.

I would clear the eeprom on all the nodes in the network you're testing, and test it specifically again.

I guess there could be a conflict if you start one node, it receives a node ID. Then turn that off and shut down the controller. Start the controller again, turn on another node. This node now receives them same node ID as the previous node. Then start the second node again. That would be a conflict, since the second node already has stored its node ID. At least that's how I think it works.

Persistence will avoid that type of conflict, yes.

**Comment by flatsiedatsie** [comment]
> I guess there could be a conflict if you start one node (call it 1), it receives a node ID 1. Then turn that off and shut down the controller. Start the controller again, turn on another node (call it 2). This node now receives them same node ID 1 as the previous node. Then start the second node (1) again. That would be a conflict, since the second node already has stored its node ID. At least that's how I think it works.

I suspect that might be it, since the overlapping ID's were low (e.g. 2), but I will make sure. It happened during a period when I was testing the add-on a lot, and this comes with a lot of reboots.

The reason I did not want to enable persistence is that this could allow very old devices to still show up in the devices list, even though they haven't been spotted for a long time / don't exist anymore. Perhaps I can get the best of both worlds by enabling persistence, but not use the persistence object to generate new devices (as is currently the case already anyway, since I took your advice on using the messages instead).
