### ISSUE TITLE
Support for the 2.0 mysensors / Local Sensor on Gateway

### ISSUE THREAD

**Issue by clyra** [theolind/pymysensors#51]
Hi,

It seems that new 2.0 version of mysensors is mostly compatible with the old 1.5 serial protocol, but there's a issue when the gateway also have some local sensors. I was getting a error message saying "Node 0 is unknow, will not add child sensor." when the gateway present his child sensors. My gateway send those messages:

    0;255;3;0;14;Gateway startup complete.
    0;255;3;0;11;My Gateway 
    0;255;3;0;12;1.0
    0;0;0;0;7;
    0;1;0;0;6;
    0;255;3;0;9;No registration required
    0;255;3;0;9;Init complete, id=0, parent=0, distance=0, registration=1
    0;1;1;0;0;28.0
    0;0;1;0;1;59.0 

As I could understand from the code, _handle_presentation was expecting a "present" message with child_id 255 to add the sensor but since it never came the node_id 0 is unknow. I did a ugly hack by adding the sensor at _handle_internal, but may a cleaner solution would be adding the gateway as a sensor at __init__ if the protocol_version is 2.0.

**Comment by MartinHjelmare** [comment]
This should preferably be fixed in the mysensors library. Until that happens, you can try this as a workaround:
```
present(255, 18);
```
Add it in the beginning of the presentation function in the sketch. The number 18 signifies S_ARDUINO_REPEATER_NODE. I tested this workaround for re-presenting a node after setup for version 1.5, but I havent' tested it yet for version 2.0.

**Comment by clyra** [comment]
Hi,

Thanks! I tried and it works with version 2.0.

**Comment by MartinHjelmare** [comment]
Closing as this has been fixed in the mysensors library:
https://github.com/mysensors/MySensors/pull/532
