### ISSUE TITLE
Problems seeing node mysensor data on home assistant dashboard using mysensors.py

### ISSUE THREAD

**Issue by den2k** [theolind/pymysensors#7]
While I am able to see beacons (see below) showing up on Terminal, I am unable to see any Nodes/sensor data on the home assistant Dashboard.  Any ideas? 

This is my log file output.

home-assistant.log
15-09-04 22:00:25 mysensors.mysensors: Error decoding message from gateway
Traceback (most recent call last):
  File "/home/pi/.homeassistant/lib/mysensors/mysensors.py", line 220, in run
    response = self.logic(msg)
  File "/home/pi/.homeassistant/lib/mysensors/mysensors.py", line 98, in logic
    msg = Message(data)
  File "/home/pi/.homeassistant/lib/mysensors/mysensors.py", line 279, in __init__
    self.decode(data)
  File "/home/pi/.homeassistant/lib/mysensors/mysensors.py", line 299, in decode
    self.sub_type) = [int(f) for f in data]
  File "/home/pi/.homeassistant/lib/mysensors/mysensors.py", line 299, in <listcomp>
    self.sub_type) = [int(f) for f in data]
ValueError: invalid literal for int() with base 10: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0

Terminal output:
INFO:homeassistant.components.sensor.mysensors:sensor_update sensor_update: node 1
INFO:homeassistant.components.sensor.mysensors:sensor_update sensor_update: node 1
INFO:homeassistant.components.sensor.mysensors:sensor_update sensor_update: node 1
INFO:homeassistant.components.sensor.mysensors:sensor_update sensor_update: node 1
INFO:homeassistant.components.sensor.mysensors:sensor_update sensor_update: node 1
INFO:homeassistant.components.sensor.mysensors:sensor_update sensor_update: node 1
INFO:homeassistant.components.sensor.mysensors:sensor_update sensor_update: node 1
INFO:homeassistant.components.sensor.mysensors:sensor_update sensor_update: node 1
INFO:homeassistant.components.sensor.mysensors:sensor_update sensor_update: node 1
INFO:homeassistant.components.sensor.mysensors:sensor_update sensor_update: node 1
INFO:homeassistant.components.sensor.mysensors:sensor_update sensor_update: node 1
INFO:homeassistant.components.sensor.mysensors:sensor_update sensor_update: node 1

**Comment by andythigpen** [comment]
HA needs to see the presentation message from the sensor in order to add it to the UI.  Most likely, the presentation message was sent before HA started, or it was only half-received -- the ValueError message in your log output typically occurs on startup because only part of a message was received.

Make sure that your sensor code sends a presentation message on startup, and try toggling your sensor off/on after HA has started.  If the presentation message is received, you should see a message in the log file like `adding new devices: ...` with a list of sensors.

You can also enable debug mode in the HA configuration section for mysensors using `debug: True`.  This should output a debug message to the log for every message received from the serial gateway, and may help you get more information.

If persistence is enabled for HA (it is by default), then the sensor information will be saved to a pickle file so that if HA restarts, the sensors do not need to send a presentation message again.  HA does need to receive at least one presentation message to create the persistence file, though.

Hope that helps.

**Comment by den2k** [comment]
Hmmm.  I've reset the node and gateway a number of times and made sure the gateway came up before turning on the node. 

I have the 
gw.present(SENSOR_ID, S_TEMP);

In my Arduino Sensor Node code.... I removed the

**Comment by MartinHjelmare** [comment]
The ValueError is now handled, see #15. The home assistant docs have been updated with a guide how to present a sensor/actuator properly:
https://home-assistant.io/components/mysensors/#presentation
